package Frames;

import java.awt.*;
import javax.swing.*;
import classes.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author anasg
 */
public class Frame_admin_search extends javax.swing.JFrame {
     DB_manager db = new DB_manager();
    private static final float DEFAULT_TRANSPARENCY = 0.5f;
    Admin_information ad;
    /**
     * Creates new form Frame_admin_search
     */
    public Frame_admin_search() {
        setIcon();
         BG("/images/Twin_tower.jpeg");
        initComponents();
    }
    
    public void BG(String imagePath){
            JPanel backgroundPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, DEFAULT_TRANSPARENCY));

                // Load image (error handling can be added)
                ImageIcon imageIcon = new ImageIcon(getClass().getResource(imagePath));
                Image image = imageIcon.getImage();

                int imageWidth = image.getWidth(null);
                int imageHeight = image.getHeight(null);

                // Tile or scale the image to fit the panel (optional customization)
                int panelWidth = getWidth();
                int panelHeight = getHeight();
                for (int y = 0; y < panelHeight; y += imageHeight) {
                    for (int x = 0; x < panelWidth; x += imageWidth) {
                        g2d.drawImage(image, x, y, this);
                    }
                }
            }
            

            }; 
            
            backgroundPanel.setOpaque(false); // Make panel transparent

        // Add your other components to the background panel here

        setContentPane(backgroundPanel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack(); // Adjust frame size if needed
        setLocationRelativeTo(null); // Center the frame on screen
        setVisible(true);
    }
    
    public void setIcon(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/ico_oop.png"));
        setIconImage(icon.getImage());
        BackgroundPanel backgroundPanel = new BackgroundPanel("/images/ico_oop.png");
        setContentPane(backgroundPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_available_planes = new javax.swing.JButton();
        Button_employees_salary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Button_excutesql = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea_sqlcommand = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data manipulation");

        Button_available_planes.setText("Available planes");
        Button_available_planes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_available_planesActionPerformed(evt);
            }
        });

        Button_employees_salary.setText("Employees salary");
        Button_employees_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_employees_salaryActionPerformed(evt);
            }
        });

        jLabel1.setText("Fast queries: ");

        Button_excutesql.setText("Exccute");
        Button_excutesql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_excutesqlActionPerformed(evt);
            }
        });

        TextArea_sqlcommand.setColumns(20);
        TextArea_sqlcommand.setRows(5);
        TextArea_sqlcommand.setText("Enter the SQL codes");
        jScrollPane2.setViewportView(TextArea_sqlcommand);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home(20X20).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 107, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_excutesql)
                        .addGap(170, 170, 170))))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_employees_salary)
                        .addGap(113, 113, 113)
                        .addComponent(Button_available_planes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_excutesql))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_available_planes)
                    .addComponent(Button_employees_salary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_excutesqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_excutesqlActionPerformed
        String Query = TextArea_sqlcommand.getText();

    try {
        ResultSet set = db.executeQuery(Query); // Assuming 'db' is a valid database connection object 
        Table.setModel(DbUtils.resultSetToTableModel(set));
    } catch (SQLException ex) {
        // Handle the exception appropriately
        ex.printStackTrace(); // At the very least, print the error to the console
        // You might want to display an error message to the user as well.
    }
    }//GEN-LAST:event_Button_excutesqlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Frame_home home = new Frame_home();
        home.setSize(528, 528);
        home.setVisible(true);
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        home.setLocationRelativeTo(null);
        this.dispose();

        System.gc();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Button_available_planesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_available_planesActionPerformed
        try {
                String Query = "SELECT * FROM planes;";
        ResultSet set = db.executeQuery(Query); // Assuming 'db' is a valid database connection object 
        Table.setModel(DbUtils.resultSetToTableModel(set));
    } catch (SQLException ex) {
        // Handle the exception appropriately
        ex.printStackTrace(); // At the very least, print the error to the console
        // You might want to display an error message to the user as well.
    }
    }//GEN-LAST:event_Button_available_planesActionPerformed

    private void Button_employees_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_employees_salaryActionPerformed
            try {
                String Query = "SELECT idEmployee ,salary FROM employees;";
        ResultSet set = db.executeQuery(Query); // Assuming 'db' is a valid database connection object 
        Table.setModel(DbUtils.resultSetToTableModel(set));
    } catch (SQLException ex) {
        // Handle the exception appropriately
        ex.printStackTrace(); // At the very least, print the error to the console
        // You might want to display an error message to the user as well.
    }
    }//GEN-LAST:event_Button_employees_salaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_admin_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_admin_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_admin_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_admin_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_admin_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_available_planes;
    private javax.swing.JButton Button_employees_salary;
    private javax.swing.JButton Button_excutesql;
    private javax.swing.JTable Table;
    private javax.swing.JTextArea TextArea_sqlcommand;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
