/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import classes.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author anasg
 */
public class Traveler_signup extends javax.swing.JFrame {

    
    
     DB_manager db = new DB_manager();
    login al;
    /**
     * Creates new form Admin_information
     */
    public Traveler_signup() {
        setIcon();
        initComponents();
    }
    public void setIcon(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/ico_oop.png"));
        setIconImage(icon.getImage());
        BackgroundPanel backgroundPanel = new BackgroundPanel("/images/ico_oop.png");
        setContentPane(backgroundPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FirstLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        RePasswordLabel = new javax.swing.JLabel();
        TextField_First = new javax.swing.JTextField();
        TextField_username = new javax.swing.JTextField();
        TextField_password = new javax.swing.JTextField();
        TextField_RePassword = new javax.swing.JTextField();
        SSNLabel = new javax.swing.JLabel();
        TextField_SSN = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        TextField_Phone = new javax.swing.JTextField();
        DobLabel = new javax.swing.JLabel();
        TextField_Birth = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        TextField_Gender = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        TextField_Address = new javax.swing.JTextField();
        Passportlabel = new javax.swing.JLabel();
        TextField_Passport = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LastLabel = new javax.swing.JLabel();
        TextField_Last = new javax.swing.JTextField();
        TextField_Middle = new javax.swing.JTextField();
        MidLabel = new javax.swing.JLabel();
        TextField_Email = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        Signup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Updating information");

        FirstLabel.setText("First Name:");

        UsernameLabel.setText("Username: ");

        PasswordLabel.setText("Password:");

        RePasswordLabel.setText("Re-enter the password: ");

        TextField_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_FirstActionPerformed(evt);
            }
        });

        TextField_RePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_RePasswordActionPerformed(evt);
            }
        });

        SSNLabel.setText("SSN:");

        PhoneLabel.setText("Phone number: ");

        TextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PhoneActionPerformed(evt);
            }
        });

        DobLabel.setText("Birth date: ");

        GenderLabel.setText("Gender: ");

        TextField_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_GenderActionPerformed(evt);
            }
        });

        AddressLabel.setText("Address: ");

        Passportlabel.setText("Passport ID: ");

        jLabel11.setText("___________________________________________");

        LastLabel.setText("Last Name:");

        TextField_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_LastActionPerformed(evt);
            }
        });

        TextField_Middle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MiddleActionPerformed(evt);
            }
        });

        MidLabel.setText("Middle Name:");

        EmailLabel.setText("Email: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DobLabel)
                            .addComponent(GenderLabel))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Gender)
                            .addComponent(TextField_Birth)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MidLabel)
                            .addComponent(FirstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_First)
                            .addComponent(TextField_Middle))))
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RePasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_RePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextField_password, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(TextField_username)))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passportlabel)
                    .addComponent(PhoneLabel)
                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField_Last, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(TextField_SSN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_Address, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_Phone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_Passport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstLabel)
                    .addComponent(TextField_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MidLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastLabel)
                    .addComponent(TextField_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_SSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passportlabel)
                    .addComponent(TextField_Passport, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DobLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailLabel)
                    .addComponent(TextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLabel)
                    .addComponent(TextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel)
                    .addComponent(TextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_RePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePasswordLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Signup.setText("Sign up");
        Signup.setToolTipText("this will take you to login page");
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_FirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_FirstActionPerformed

    private void TextField_RePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_RePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_RePasswordActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        //updating the information on the database then also handle input errors:
        String passengersinsertQuery = "INSERT INTO passengers (  Passenger_username , Passenger_password , idPassport , ssn ) VALUES (?, ?, ? , ?) ";
        String personsinsertQuery = "INSERT INTO persons (first_Name, Middle_name, Family_name, Date_of_birth, Gender, Phone, Email, Address, SSN) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
    String username = TextField_username.getText();
    String password = TextField_password.getText();
    String Repassword = TextField_RePassword.getText();
    String idPassport = TextField_Passport.getText();
    String ssn = TextField_SSN.getText();        
    
    
    String firstName = TextField_First.getText();
    String middleName = TextField_Middle.getText();
    String lastName = TextField_Last.getText();
    String dateOfBirth = TextField_Birth.getText();
    String gender = TextField_Gender.getText();
    String phone = TextField_Phone.getText();
    String email = TextField_Email.getText();
    String address = TextField_Address.getText();
    
            if(password.equals(Repassword)){
             try {
             // Update persons table
             db.executePreparedStatement(personsinsertQuery, firstName, middleName, lastName, dateOfBirth, gender, phone, email, address, ssn);
             
             // Handle update success
             // ... (show success message, proceed to login)
         } catch (SQLException ex) {
             Logger.getLogger(Admin_information.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
             // ... Retrieve other values from text field
             
             // Update passengers table
             db.executePreparedStatement(passengersinsertQuery, username, password, idPassport,ssn);
         } catch (SQLException ex) {
             Logger.getLogger(Admin_information.class.getName()).log(Level.SEVERE, null, ex);
         }


        }
            else { // Passwords don't match
    JOptionPane.showMessageDialog(this, "The passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
}
        //also in the construct pass the username and password so it read the informations in needed frames
        Traveler_chose_fligth nextframe = new Traveler_chose_fligth();
        nextframe.setVisible(true);
        nextframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        nextframe.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_SignupActionPerformed

    private void TextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PhoneActionPerformed

    private void TextField_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_GenderActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_TextField_GenderActionPerformed

    private void TextField_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_LastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_LastActionPerformed

    private void TextField_MiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MiddleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_MiddleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traveler_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traveler_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traveler_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traveler_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traveler_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel DobLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FirstLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel LastLabel;
    private javax.swing.JLabel MidLabel;
    private javax.swing.JLabel Passportlabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JLabel RePasswordLabel;
    private javax.swing.JLabel SSNLabel;
    private javax.swing.JButton Signup;
    private javax.swing.JTextField TextField_Address;
    private javax.swing.JTextField TextField_Birth;
    private javax.swing.JTextField TextField_Email;
    private javax.swing.JTextField TextField_First;
    private javax.swing.JTextField TextField_Gender;
    private javax.swing.JTextField TextField_Last;
    private javax.swing.JTextField TextField_Middle;
    private javax.swing.JTextField TextField_Passport;
    private javax.swing.JTextField TextField_Phone;
    private javax.swing.JTextField TextField_RePassword;
    private javax.swing.JTextField TextField_SSN;
    private javax.swing.JTextField TextField_password;
    private javax.swing.JTextField TextField_username;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
