/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.*;
import javax.swing.*;
import classes.*;
import java.sql.*;


import java.time.LocalDateTime;
import org.apache.commons.dbutils.DbUtils;

/**
 *
 * @author anasg
 */
public class Traveler_chose_fligth extends javax.swing.JFrame {
    DB_manager db = new DB_manager();
    private static final float DEFAULT_TRANSPARENCY = 0.5f;
    String idFlights, destination, origin, idPlane;
    String arrivalTime, departureTime;
    
    /**
     * Creates new form Traveler_chose_fligth
     */
    
    
    //programer defined instences
   // private Frame_home home_frame;//@anas
 
  
    public Traveler_chose_fligth() {   //constructor 1
        setIcon();
        //BG("/images/chris-karidis-nnzkZNYWHaU-unsplash.jpeg");
        initComponents();
        Button_to_traveler_info_frame.setEnabled(false);
        populateComboBox(jComboBox3, "SELECT DISTINCT Origin FROM flights");
        populateComboBox(jComboBox1, "SELECT DISTINCT Destination FROM flights");
    }

    
//        public void BG(String imagePath){
//            JPanel backgroundPanel = new JPanel() {
//           @Override
//            protected void paintComponent(Graphics g) {
//                super.paintComponent(g);
//                Graphics2D g2d = (Graphics2D) g.create();
//                g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, DEFAULT_TRANSPARENCY));
//
//               // Load image (error handling can be added)
//                ImageIcon imageIcon = new ImageIcon(getClass().getResource(imagePath));
//                Image image = imageIcon.getImage();
//
//                int imageWidth = image.getWidth(null);
//                int imageHeight = image.getHeight(null);
//
//                int panelWidth = getWidth();
//                int panelHeight = getHeight();
//               for (int y = 0; y < panelHeight; y += imageHeight) {
//                   for (int x = 0; x < panelWidth; x += imageWidth) {
//                       g2d.drawImage(image, x, y, this);
//                   }
//                }
//           }
//           
//
//          }; 
//          
//           backgroundPanel.setOpaque(false); // Make panel transparent
//        // Add your other components to the background panel here
//
//        setContentPane(backgroundPanel);
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//       pack(); // Adjust frame size if needed
//        setLocationRelativeTo(null); // Center the frame on screen
//        setVisible(true);
//        
//   }
//
//
//    
    public void setIcon(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/ico_oop.png"));
        setIconImage(icon.getImage());
        BackgroundPanel backgroundPanel = new BackgroundPanel("/images/chris-karidis-nnzkZNYWHaU-unsplash.jpeg");
        setContentPane(backgroundPanel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_to_home = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Button_to_traveler_info_frame = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chose a flight");

        Button_to_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home(20X20).png"))); // NOI18N
        Button_to_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_to_homeActionPerformed(evt);
            }
        });

        jLabel2.setText("From:");

        jLabel3.setText("To:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select departure" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Button_to_traveler_info_frame.setText("Prossed ");
        Button_to_traveler_info_frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_to_traveler_info_frameActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("displaying all available fligths that has \navailable seats");
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "available fligth numbers", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select origin" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_to_traveler_info_frame)
                        .addGap(202, 202, 202))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(14, 14, 14)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 292, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Button_to_traveler_info_frame)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_to_home)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Button_to_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void Button_to_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_to_homeActionPerformed
        Frame_home home_frame= new Frame_home();
        home_frame.setVisible(true);
        home_frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        home_frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Button_to_homeActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(!(jComboBox2.getSelectedIndex() == 0)){
        Button_to_traveler_info_frame.setEnabled(true);
        }
        else{
            Button_to_traveler_info_frame.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void Button_to_traveler_info_frameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_to_traveler_info_frameActionPerformed
 try {
             db.connect();
             PreparedStatement pstmt = db.getConnection().prepareStatement("SELECT * from Flights where idFlights = ?");
             pstmt.setString(1, jComboBox2.getSelectedItem().toString());
             ResultSet rs = pstmt.executeQuery();
             Flight f =  new Flight();
             while(rs.next()){
             
             f.createInstance(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6));
             }
           db.closeConnection();
         }
         
         catch (Exception e) {
             e.printStackTrace();
         }
        
        Traveler_info frameTravelerinfo = new Traveler_info();    // new Traveler_info(home_frame,this)@anas i am making a chain to save the frames
        frameTravelerinfo.setVisible(true);
        frameTravelerinfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameTravelerinfo.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_Button_to_traveler_info_frameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Select fligth");
        
        try{
            db.connect();
            String text1 = "idFlights\tArrival_Time\t\tDeparture_Time\tidPlane\n";
            PreparedStatement pstmt = db.getConnection().prepareStatement("SELECT * FROM flights WHERE Origin = ? AND Destination = ?");
            pstmt.setString(1, jComboBox3.getSelectedItem().toString());
            pstmt.setString(2, jComboBox1.getSelectedItem().toString());
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                //int i = 1;
                text1 += rs.getString(1) + "\t" + rs.getString(2) + "\t" + rs.getString(3) +  "\t" + rs.getString(6) + "\n";
                jTextArea1.setText(text1);
                jComboBox2.addItem(rs.getString(1));
                //i++;
            }
            db.closeConnection();
        }
        
        catch (Exception e){
            e.printStackTrace();
        }    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traveler_chose_fligth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traveler_chose_fligth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traveler_chose_fligth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traveler_chose_fligth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Traveler_chose_fligth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_to_home;
    private javax.swing.JButton Button_to_traveler_info_frame;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables




private void populateComboBox(JComboBox<String> comboBox, String query){
        try {
            db.connect();
            PreparedStatement pst = db.getConnection().prepareStatement(query);
            ResultSet rs = pst.executeQuery();
                    
            while (rs.next()) {
                comboBox.addItem(rs.getString(1));
            }
            db.closeConnection();
        }
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while fetching data from the database.");
        }
    }
    
   




}
